DROP INDEX GBA_SP_SI;

truncate table gba.site_point;
commit;

DROP SEQUENCE SITE_POINT_SEQ;

CREATE SEQUENCE SITE_POINT_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
 START WITH 100000
/

GRANT SELECT ON SITE_POINT_SEQ TO GBA_USER
/

CREATE INDEX GBA_SP_SI ON GBA.SITE_POINT(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=point,sdo_indx_dims=2,tablespace=GBA_INDEXES') PARALLEL;
