select
  T.*
from
  GBA.TRANSPORT_LINE t
  join GBA.INTEGRATION_SESSION_POLY CS on T.CREATE_INTEGRATION_SESSION_ID = CS.INTEGRATION_SESSION_POLY_ID
  join GBA.INTEGRATION_SESSION_POLY MS on T.MODIFY_INTEGRATION_SESSION_ID = MS.INTEGRATION_SESSION_POLY_ID
where
  CS.SESSION_COMMIT_DATE <= [DATE] AND MS.SESSION_COMMIT_DATE <= [DATE]
