CREATE TABLE  "FEATURE_STATUS_CODE"
(
	"FEATURE_STATUS_CODE" VARCHAR2(1) NOT NULL,
	"DESCRIPTION" VARCHAR2(30) NOT NULL,
	"CREATE_INTEGRATION_SESSION_ID" NUMBER(10) NOT NULL,
	"MODIFY_INTEGRATION_SESSION_ID" NUMBER(10) NOT NULL,
	CONSTRAINT "GBA_FSC_PK" PRIMARY KEY ("FEATURE_STATUS_CODE"),
	CONSTRAINT "GBA_FSC_C_GBA_ISP_FK" FOREIGN KEY ("CREATE_INTEGRATION_SESSION_ID") REFERENCES  "INTEGRATION_SESSION_POLY" ("INTEGRATION_SESSION_POLY_ID"),
	CONSTRAINT "GBA_FSC_M_GBA_ISP_FK" FOREIGN KEY ("MODIFY_INTEGRATION_SESSION_ID") REFERENCES  "INTEGRATION_SESSION_POLY" ("INTEGRATION_SESSION_POLY_ID")
)
;
CREATE INDEX "GBA_FSC_C_GBA_ISP_FK_I"
 ON  "FEATURE_STATUS_CODE" ("CREATE_INTEGRATION_SESSION_ID") 
TABLESPACE	GBA_INDEXES
;
CREATE INDEX "GBA_FSC_M_GBA_ISP_FK_I"
 ON  "FEATURE_STATUS_CODE" ("MODIFY_INTEGRATION_SESSION_ID") 
TABLESPACE	GBA_INDEXES
;

COMMENT ON TABLE  "FEATURE_STATUS_CODE" IS 'The FEATURE STATUS CODE is a code that indicates the status of a spatial feature (record). For example; A=Active, P=Planned, R=Retired.'
;

COMMENT ON COLUMN  "FEATURE_STATUS_CODE"."FEATURE_STATUS_CODE" IS 'The FEATURE STATUS CODE is a code that indicates the status of a spatial feature (record). For example; A=Active, P=Planned, R=Retired.'
;

COMMENT ON COLUMN  "FEATURE_STATUS_CODE"."DESCRIPTION" IS 'DESCRIPTION is the display quality description of the code value.'
;

COMMENT ON COLUMN  "FEATURE_STATUS_CODE"."CREATE_INTEGRATION_SESSION_ID" IS 'CREATE_INTEGRATION_SESSION_ID is the INTEGRATION SESSION POLY where the record was first created.'
;

COMMENT ON COLUMN  "FEATURE_STATUS_CODE"."MODIFY_INTEGRATION_SESSION_ID" IS 'MODIFY_INTEGRATION_SESSION_ID is the INTEGRATION SESSION POLY where the record was last modified.'
;

GRANT DELETE,INSERT,SELECT,UPDATE ON  "FEATURE_STATUS_CODE" TO gba_user
;

GRANT SELECT ON  "FEATURE_STATUS_CODE" TO gba_viewer
;