CREATE TABLE  "SITE_LOCATION_CODE"
(
	"SITE_LOCATION_CODE" VARCHAR2(1) NOT NULL,
	"DESCRIPTION" VARCHAR2(30) NOT NULL,
	"CREATE_INTEGRATION_SESSION_ID" NUMBER(10) NOT NULL,
	"MODIFY_INTEGRATION_SESSION_ID" NUMBER(10) NOT NULL,
	CONSTRAINT "GBA_SLC_PK" PRIMARY KEY ("SITE_LOCATION_CODE"),
	CONSTRAINT "GBA_SLC_C_GBA_ISP_FK" FOREIGN KEY ("CREATE_INTEGRATION_SESSION_ID") REFERENCES  "INTEGRATION_SESSION_POLY" ("INTEGRATION_SESSION_POLY_ID"),
	CONSTRAINT "GBA_SLC_M_GBA_ISP_FK" FOREIGN KEY ("MODIFY_INTEGRATION_SESSION_ID") REFERENCES  "INTEGRATION_SESSION_POLY" ("INTEGRATION_SESSION_POLY_ID")
)
;
CREATE INDEX "GBA_SLC_C_GBA_ISP_FK_I"
 ON  "SITE_LOCATION_CODE" ("CREATE_INTEGRATION_SESSION_ID") 
TABLESPACE	GBA_INDEXES
;
CREATE INDEX "GBA_SLC_M_GBA_ISP_FK_I"
 ON  "SITE_LOCATION_CODE" ("MODIFY_INTEGRATION_SESSION_ID") 
TABLESPACE	GBA_INDEXES
;

COMMENT ON TABLE  "SITE_LOCATION_CODE" IS 'The SITE LOCATION CODE is a code that indicates the conceptual location of the point geometry in relation to the site. For example; A=Access, B=Back Door, F=Front Door, P=Parcel, R=Rooftop.'
;

COMMENT ON COLUMN  "SITE_LOCATION_CODE"."SITE_LOCATION_CODE" IS 'The SITE LOCATION CODE is a code that indicates the conceptual location of the point geometry in relation to the site. For example; A=Access, B=Back Door, F=Front Door, P=Parcel, R=Rooftop.'
;

COMMENT ON COLUMN  "SITE_LOCATION_CODE"."DESCRIPTION" IS 'DESCRIPTION is the display quality description of the code value.'
;

COMMENT ON COLUMN  "SITE_LOCATION_CODE"."CREATE_INTEGRATION_SESSION_ID" IS 'CREATE_INTEGRATION_SESSION_ID is the INTEGRATION SESSION POLY where the record was first created.'
;

COMMENT ON COLUMN  "SITE_LOCATION_CODE"."MODIFY_INTEGRATION_SESSION_ID" IS 'MODIFY_INTEGRATION_SESSION_ID is the INTEGRATION SESSION POLY where the record was last modified.'
;

GRANT DELETE,INSERT,SELECT,UPDATE ON  "SITE_LOCATION_CODE" TO gba_user
;

GRANT SELECT ON  "SITE_LOCATION_CODE" TO gba_viewer
;