


CREATE INDEX GBA_SP_SI ON gba.SITE_POINT USING GIST (GEOMETRY);

CREATE INDEX GBA_SP_N_GBA_SN_FK_I ON GBA.SITE_POINT(STREET_NAME_ID) ;
CREATE INDEX GBA_SP_1_GBA_SN_FK_I ON GBA.SITE_POINT(STREET_NAME_ALIAS_1_ID) ;
CREATE INDEX GBA_SP_C_GBA_PO_FK_I ON GBA.SITE_POINT(CREATE_PARTNER_ORG_ID) ;
CREATE INDEX GBA_SP_GBA_CP_FK_I ON GBA.SITE_POINT(COMMUNITY_ID) ;
CREATE INDEX GBA_SP_GBA_FSC_FK_I ON GBA.SITE_POINT(FEATURE_STATUS_CODE) ;
CREATE INDEX GBA_SP_GBA_LP_FK_I ON GBA.SITE_POINT(LOCALITY_ID) ;
CREATE INDEX GBA_SP_GBA_RDP_FK_I ON GBA.SITE_POINT(REGIONAL_DISTRICT_ID) ;
CREATE INDEX GBA_SP_GBA_SLC_FK_I ON GBA.SITE_POINT(SITE_LOCATION_CODE) ;
CREATE INDEX GBA_SP_GBA_STC_FK_I ON GBA.SITE_POINT(SITE_TYPE_CODE) ;
CREATE INDEX GBA_SP_GBA_TL_FK_I ON GBA.SITE_POINT(TRANSPORT_LINE_ID) ;
CREATE INDEX GBA_SP_M_GBA_PO_FK_I ON GBA.SITE_POINT(MODIFY_PARTNER_ORG_ID) ;
CREATE INDEX GBA_SP_P_GBA_SP_FK_I ON GBA.SITE_POINT(PARENT_SITE_ID) ;
CREATE INDEX GBA_SP_U_GBA_PO_FK_I ON GBA.SITE_POINT(CUSTODIAN_PARTNER_ORG_ID) ;
