INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES('SITE_POINT','GEOMETRY',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', 263000, 1876000, 1),MDSYS.SDO_DIM_ELEMENT('Y', 356000, 1738000, 1)),3005);
INSERT INTO OGIS_GEOMETRY_COLUMNS(F_TABLE_SCHEMA,F_TABLE_NAME,F_GEOMETRY_COLUMN,G_TABLE_SCHEMA,G_TABLE_NAME,GEOMETRY_TYPE,COORD_DIMENSION,SRID) VALUES('GBA','SITE_POINT','GEOMETRY','GBA','SITE_POINT',1,2,1003005);

CREATE INDEX GBA_SP_SI ON SITE_POINT(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS ('layer_gtype=mulitpoint,sdo_indx_dims=2,tablespace=GBA_INDEXES') PARALLEL;

CREATE INDEX GBA_SP_N_GBA_SN_FK_I ON GBA.SITE_POINT(STREET_NAME_ID) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_1_GBA_SN_FK_I ON GBA.SITE_POINT(STREET_NAME_ALIAS_1_ID) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_C_GBA_PO_FK_I ON GBA.SITE_POINT(CREATE_PARTNER_ORG_ID) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_GBA_CP_FK_I ON GBA.SITE_POINT(COMMUNITY_ID) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_GBA_FSC_FK_I ON GBA.SITE_POINT(FEATURE_STATUS_CODE) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_GBA_LP_FK_I ON GBA.SITE_POINT(LOCALITY_ID) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_GBA_RDP_FK_I ON GBA.SITE_POINT(REGIONAL_DISTRICT_ID) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_GBA_SLC_FK_I ON GBA.SITE_POINT(SITE_LOCATION_CODE) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_GBA_STC_FK_I ON GBA.SITE_POINT(SITE_TYPE_CODE) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_GBA_TL_FK_I ON GBA.SITE_POINT(TRANSPORT_LINE_ID) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_M_GBA_PO_FK_I ON GBA.SITE_POINT(MODIFY_PARTNER_ORG_ID) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_P_GBA_SP_FK_I ON GBA.SITE_POINT(PARENT_SITE_ID) TABLESPACE GBA_INDEXES;
CREATE INDEX GBA_SP_U_GBA_PO_FK_I ON GBA.SITE_POINT(CUSTODIAN_PARTNER_ORG_ID) TABLESPACE GBA_INDEXES;
