CREATE TABLE  SITE_TYPE_CODE
(
	SITE_TYPE_CODE VARCHAR(7) NOT NULL,
	DESCRIPTION VARCHAR(30) NOT NULL,
	CREATE_INTEGRATION_SESSION_ID NUMERIC(10) NOT NULL,
	MODIFY_INTEGRATION_SESSION_ID NUMERIC(10) NOT NULL,
	CONSTRAINT GBA_STC_PK PRIMARY KEY (SITE_TYPE_CODE),
	CONSTRAINT GBA_STC_C_GBA_ISP_FK FOREIGN KEY (CREATE_INTEGRATION_SESSION_ID) REFERENCES  INTEGRATION_SESSION_POLY (INTEGRATION_SESSION_POLY_ID),
	CONSTRAINT GBA_STC_M_GBA_ISP_FK FOREIGN KEY (MODIFY_INTEGRATION_SESSION_ID) REFERENCES  INTEGRATION_SESSION_POLY (INTEGRATION_SESSION_POLY_ID)
)
;
CREATE INDEX GBA_STC_C_GBA_ISP_FK_I
 ON  SITE_TYPE_CODE (CREATE_INTEGRATION_SESSION_ID) 

;
CREATE INDEX GBA_STC_M_GBA_ISP_FK_I
 ON  SITE_TYPE_CODE (MODIFY_INTEGRATION_SESSION_ID) 

;

COMMENT ON TABLE  SITE_TYPE_CODE IS 'The SITE TYPE CODE is a code that indicates the type of site. For example; AIR_HLI=Air Heliport, AMB_STN=Ambulance Station, COM_IND=Commercial Industrial, PRL_MNI=Park Municipal, RES_SFH=Residential Single Family, TRL_TRH=Trail Head.'
;

COMMENT ON COLUMN  SITE_TYPE_CODE.SITE_TYPE_CODE IS 'The SITE TYPE CODE is a code that indicates the type of site. For example; AIR_HLI=Air Heliport, AMB_STN=Ambulance Station, COM_IND=Commercial Industrial, PRL_MNI=Park Municipal, RES_SFH=Residential Single Family, TRL_TRH=Trail Head.'
;

COMMENT ON COLUMN  SITE_TYPE_CODE.DESCRIPTION IS 'DESCRIPTION is the display quality description of the code value.'
;

COMMENT ON COLUMN  SITE_TYPE_CODE.CREATE_INTEGRATION_SESSION_ID IS 'CREATE_INTEGRATION_SESSION_ID is the INTEGRATION SESSION POLY where the record was first created.'
;

COMMENT ON COLUMN  SITE_TYPE_CODE.MODIFY_INTEGRATION_SESSION_ID IS 'MODIFY_INTEGRATION_SESSION_ID is the INTEGRATION SESSION POLY where the record was last modified.'
;

GRANT DELETE,INSERT,SELECT,UPDATE ON  SITE_TYPE_CODE TO gba_user
;

GRANT SELECT ON  SITE_TYPE_CODE TO gba_viewer
;
